import { tv } from 'tailwind-variants';

export const variants = tv({
  base: [
    'w-full',
    'h-8',
    'appearance-none',
    'border-none',
    'rounded-sm',
    'bg-transparent',
    'cursor-pointer',
    '[&::-webkit-slider-runnable-track]:h-8',
    '[&::-webkit-slider-runnable-track]:rounded-sm',
    '[&::-webkit-slider-thumb]:appearance-none',
    '[&::-webkit-slider-thumb]:size-16',
    '[&::-webkit-slider-thumb]:rounded-full',
    '[&::-webkit-slider-thumb]:bg-primary',
    '[&::-webkit-slider-thumb]:cursor-grab',
    '[&::-webkit-slider-thumb]:active:cursor-grabbing',
    '[&::-webkit-slider-thumb]:mt-[-4px]',
    '[&::-moz-range-track]:h-8',
    '[&::-moz-range-track]:rounded-sm',
    '[&::-moz-range-thumb]:size-16',
    '[&::-moz-range-thumb]:rounded-full',
    '[&::-moz-range-thumb]:bg-primary',
    '[&::-moz-range-thumb]:cursor-grab',
    '[&::-moz-range-thumb]:active:cursor-grabbing',
    '[&::-moz-range-thumb]:border-0',
  ],
});
